apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  annotations:
    # Wave 1 — gp3 StorageClass must exist before postgres and loki claim PVCs
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asyachin/gitops-multicloud-aks-eks-receipt-app
    targetRevision: dev
    path: app/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
