---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAzm48J5mnTnitlf3u1nf/FqJ5MPrM7xf+K4mbP2UW2KKlxHMrT7mXxL5zJdLOfAf9kh+Ev3+bmiImDyR7mxJQE9DNZgYubi8bNDcimrMh+9YwRCs7GHstc/aj2WGO60n6hp6wAHNw3U7ypNQDIUtQOQ8qlYUH7U2z5nT/bS6hT1Jd49Ua9PoEXjuGWv5Gr4Ib7S1r0Ib/Z2jXYb0f3K1hxRkXQryVgqcdM4plfahjqehMF2VfQiPdg1Zu4RJc2sv20TT2NrLP4tt0vq6AWn190bpRtzeb7sp7RWSfXk+WX7ykEt5jR3aO4feFctT7jvicI31wIcx6PICNTgiIdy5drUK74Zujdpyw/kmlJ9ajSbgg5v0fGqewMhW/QbNWsxMOIxRHEdwNlI0990AqeTGPy2UkgcUmO+QZH8dUjBUkceiFAtGI20rnFRtroMOdrm91zwqKcfI8AE3qPnH4FNIbG1Rg9O2sg2PJb53NS4mn9+MGiA5gtGP3Rx9JPF5uPnoJPAAGL8mG1sMiKq7XALsHVCLORbGmbd3eU6qMguGOZj+wxXWcGFWziwbCsRJWOPi46Euy8lGXX0cXvveO/0LyN5fkjrP4k1uujeLpq+SXyouS/DNwZWr1sXPD5smeBpKPR2NvN+UY4Xida8p3lPLXy6dSSoqNUjDG+QoPmEq34xUfX9czfqzDFAGQo0L/4uTy4QFpg5QIizl9fTFpP
    admin-user: AgC8Z1XSNZpxVkuj/afS0BSacFXprLJaNOZ9+g896se1vs0+nTM+rjYLj7DxKkNARYLwGkksA2IixzIuZWIYF6tjyREhJkkA2WcVJs/YpLHh9EtKFP3M0fWGLZWPlwstsrRfOZWsfFsctqxHHA7yGa1RiKxDU4wx2EJsraCjydujPRF7ni5b/3xFPiGYboexkn3rrW8H0pltK8X5S9ioHBrjyMcjfIeKVHKkkQTdS9CsflmMzdrRnaeKxJm63R8cmuoiyVBugX+T9/X0F1ppdM+hK0F3uvTT7opJqk6KCqAGuLuhe9FAygkNDjQ6b1wraQiwjUF9MxDn720AGIpMtCejv+hhYVDMGI+96rSEmtVEkPbyntJoKbg4zefjQou0s1d5dnwstfzfoPWanHDFduRE3mp4Zh0g2HAN2+1+x1Ztdc6KPiOy0LIrfRTSAJzp/qiLbJGu/OoerqKyD1ia022/fE80+Sq15w4s9YRvg9pnmr+eqImSlo6VT5dTVhTOHH6z0l2SO2FJ+tshYs+A1tzPF3JEYTYOzZJOH9AtMtGdJRtaTEqxXWdaMfytRGwbLS5BLmrt1NtKglygZsMQrsgcBRYlhfcF0KWl3ILv0JqZX5AUZPaFHGG8ZtgRKjR45wjOeElOAFF9AyERvmTSwXSZXv31hzlkqplzVxvzPSpqVt2JGrYSl8+z4edKxCcxUkemloo4TQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
